services:
  postgres-1:
    image: postgres:15-alpine
    container_name: ${ORDERS_DB_HOST}
    environment:
      - POSTGRES_DB=${ORDERS_DB_NAME}
      - POSTGRES_USER=${ORDERS_DB_USER}
      - POSTGRES_PASSWORD=${ORDERS_DB_PASS}
    volumes:
      - pgdata1:/var/lib/postgresql/data
      - ./sql/init_db1.sql:/docker-entrypoint-initdb.d/init_db1.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $ORDERS_DB_USER"]
      interval: 5s
      retries: 5
    ports:
      - 5440:5432
    networks:
      - airflow-net

  postgres-2:
    image: postgres:15-alpine
    container_name: ${ORDERS_DB_EUR_HOST}
    environment:
      - POSTGRES_DB=${ORDERS_DB_EUR_NAME}
      - POSTGRES_USER=${ORDERS_DB_EUR_USER}
      - POSTGRES_PASSWORD=${ORDERS_DB_EUR_PASS}
    volumes:
      - pgdata2:/var/lib/postgresql/data
      - ./sql/init_db2.sql:/docker-entrypoint-initdb.d/init_db2.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $ORDERS_DB_EUR_USER"]
      interval: 5s
      retries: 5
    ports:
      - 5441:5432
    networks:
      - airflow-net
  airflow:
    build:
      context: .
      dockerfile: DockerFile_AirFlow
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
    networks:
      - airflow-net
    env_file:
      - .env

networks:
  airflow-net:
    driver: bridge

volumes:
  pgdata1:
  pgdata2: